[build]
cmd = """
cd frontend &&
trunk serve
"""

[custom.clean]
cmd = "cargo clean"
run = false

[custom.setup]
cmd = """
rustup install stable &&
rustup default stable &&
rustup target add wasm32-unknown-unknown &&
yarn global add tailwindcss &&
cargo install trunk &&
cargo install wasm-bindgen-cli
"""
run = false

[pre.fmt]
cmd = "cd frontend && cargo fmt"
